version: '3.7'
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.production
    environment:
      NEXT_PUBLIC_API_URL: http://68.183.30.186/api/v1
    ports:
      - '3000:3000'
